version: '3'
services:
    postgres:
      image: 'postgres:latest'
      environment: 
        - POSTGRES_PASSWORD=postgres_password
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
    redis:
      image: 'redis:latest'
    nginx:
      restart: always
      build: 
        dockerfile: Dockerfile.dev
        context: ./nginx
      ports: 
        - '0010:80'
    api:
      build: 
        dockerfile: Dockerfile.dev
        context: ./server
      volumes: 
        - /usr/app/node_modules
        - ./server:/usr/app
      environment: 
        - PG_USER=postgres
        - PG_HOST=postgres
        - PG_DB=postgres
        - PG_PWD=postgres_password
        - PG_PORT=5432 
        - REDIS_HOST=redis
        - REDIS_PORT=6379
    client:
      build: 
        dockerfile: Dockerfile.dev
        context: ./client
      volumes: 
        - /usr/app/node_modules
        - ./client:/usr/app
    worker:
      build: 
        dockerfile: Dockerfile.dev
        context: ./worker
      volumes: 
        - /usr/app/node_modules
        - ./worker:/usr/app